# MAJOR PROJECT 1

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


NOW READING THE FILE OR DATA WE WANT TO ANALYSE

In [ ]:
# opening the file
df = pd.read_csv(r"C:\Users\deept\Documents/Corona_NLP.csv", encoding='latin1')
df.head()

UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

In [ ]:
df.shape

(41157, 6)

## REMOVING NULL VALUES

In [ ]:
df.isnull().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [ ]:
# removing the null from the data
df1 = df.dropna()
df1


UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
5          3804       48756     ÜT: 36.319708,-82.363649  16-03-2020   
6          3805       48757          35.926541,-78.753267  16-03-2020   
...         ...         ...                           ...         ...   
41147     44946       89898                  Brooklyn, NY  14-04-2020   
41149     44948       89900              Toronto, Ontario  14-04-2020   
41150     44949       89901                          OHIO  14-04-2020   
41152     44951       89903  Wellington City, New Zealand  14-04-2020   
41156     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral  
1      advice Talk to your neighbours family to excha...  Positive  
2      Coronavirus Australia: Woolworths to give elde...  Positive  
5      As news of the region’s first confirmed COVID...  Positive  
6      Cashier at grocery store was sharing his insig...  Positive  
...                                                  ...       ...  
41147  Y’all really shitting that much more at home?...  Negative  
41149  Still shocked by the number of #Toronto superm...  Negative  
41150  I never that we’d be in a situation &amp; wor...  Positive  
41152  Airline pilots offering to stock supermarket s...   Neutral  
41156  @TartiiCat Well new/used Rift S are going for ...  Negative  

[32567 rows x 6 columns]

In [ ]:

df1.isnull().sum()  # null values removed

UserName         0
ScreenName       0
Location         0
TweetAt          0
OriginalTweet    0
Sentiment        0
dtype: int64

In [ ]:
df1.shape

(32567, 6)

In [ ]:
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
sw = stopwords.words('english')
lm = WordNetLemmatizer()

In [ ]:
df1['Sentiment'].value_counts()

Positive              9110
Negative              7763
Neutral               6172
Extremely Positive    5273
Extremely Negative    4249
Name: Sentiment, dtype: int64

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\deept\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\deept\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\deept\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

## Preprocess the Covid tweets based on the following parameter:

### A) Tokenizing words

### B) Convert words to lower case

### C) Removing Punctuations

### D) Removing Stop words


### E) Stemming or lemmatizing the words

In [ ]:
msg = []
for i in df1['OriginalTweet']:
    t = re.sub('[^A-Za-z0-9]',' ',i)  # removes  punctuations
    t = t.lower()                     # converting  words to lower case
    t = word_tokenize(t)              # tokenizing  words
    t= [i for i in t if i not in sw]  # removes stop words
    t = [lm.lemmatize(i) for i in t]  # lemmatization of words
    t = " ".join(t)                   # joining sentences
    msg.append(t)

In [ ]:
print(msg[:10])

['menyrbie phil gahan chrisitv http co ifz9fan2pa http co xx6ghgfzcc http co i2nlzdxno8', 'advice talk neighbour family exchange phone number create contact list phone number neighbour school employer chemist gp set online shopping account po adequate supply regular med order', 'coronavirus australia woolworth give elderly disabled dedicated shopping hour amid covid 19 outbreak http co binca9vp8p', 'news region first confirmed covid 19 case came sullivan county last week people flocked area store purchase cleaning supply hand sanitizer food toilet paper good tim dodson report http co cfxch7a2lu', 'cashier grocery store sharing insight covid 19 prove credibility commented civics class know talking http co iefdnehgdo', 'supermarket today buy toilet paper rebel toiletpapercrisis covid 19 http co evxkqlidaz', 'due covid 19 retail store classroom atlanta open walk business class next two week beginning monday march 16 continue process online phone order normal thank understanding http co kw

## Transform the words into vectors using Count Vectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=2000)
sm = cv.fit_transform(msg).toarray()

In [ ]:
print(len(cv.get_feature_names_out()))

2000


In [ ]:
sm.shape

(32567, 2000)

In [ ]:
print(len(sm[0]))
print(len(sm[87]))

2000
2000


## CONVERT--SENTIMENTS----
### EXTREMLEY POSITIVE ---> POSITIVE
### EXTREMELY NEGATIVE ---> NEGATIVE

In [ ]:
df2 = df1.replace(to_replace ="Extremely Positive",
                 value ="Positive")

In [ ]:
df3 =df2.replace(to_replace ="Extremely Negative",
                 value ="Negative")

In [ ]:
df3.head(10)

UserName  ScreenName                   Location     TweetAt  \
0       3799       48751                     London  16-03-2020   
1       3800       48752                         UK  16-03-2020   
2       3801       48753                  Vagabonds  16-03-2020   
5       3804       48756  ÜT: 36.319708,-82.363649  16-03-2020   
6       3805       48757       35.926541,-78.753267  16-03-2020   
7       3806       48758                    Austria  16-03-2020   
8       3807       48759            Atlanta, GA USA  16-03-2020   
9       3808       48760           BHAVNAGAR,GUJRAT  16-03-2020   
10      3809       48761             Makati, Manila  16-03-2020   
11      3810       48762  Pitt Meadows, BC, Canada   16-03-2020   

                                        OriginalTweet Sentiment  
0   @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral  
1   advice Talk to your neighbours family to excha...  Positive  
2   Coronavirus Australia: Woolworths to give elde...  Positive  
5   As news of the region’s first confirmed COVID...  Positive  
6   Cashier at grocery store was sharing his insig...  Positive  
7   Was at the supermarket today. Didn't buy toile...   Neutral  
8   Due to COVID-19 our retail store and classroom...  Positive  
9   For corona prevention,we should stop to buy th...  Negative  
10  All month there hasn't been crowding in the su...   Neutral  
11  Due to the Covid-19 situation, we have increas...  Positive

In [ ]:
df3['Sentiment'].value_counts()

Positive    14383
Negative    12012
Neutral      6172
Name: Sentiment, dtype: int64

## CONVERTING POSITIVE ,NEGATIVE ,NEUTRAL TEXT INTO BINARY

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df3['Sentiment'] = lb.fit_transform(df3['Sentiment'])

## ASSIN-
### POSITIVE TWEETS ---> 2
### NEGATIVE TWEETS ---> 0
### NEUTRAL  TWEETS ---> 1

In [ ]:
df3['Sentiment'].value_counts()

2    14383
0    12012
1     6172
Name: Sentiment, dtype: int64

In [ ]:
x = sm
y = df3['Sentiment']
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


## SPLITING DATA INTO TRAINING AND TEST DATA

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24425, 2000)
(8142, 2000)
(24425,)
(8142,)


## Multinomial Naïve Bayes Classification

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
m1 = MultinomialNB()

In [ ]:
m1.fit(x_train,y_train)

MultinomialNB()

In [ ]:
print("training score",m1.score(x_train,y_train))
print("testing score",m1.score(x_test,y_test))

training score 0.7086591606960082
testing score 0.6868091378039793


## PREDICTING THE SENTIMENT

In [ ]:
ypred_m1 = m1.predict(x_test)
print("The predicted sentiment", ypred_m1)

The predicted sentiment [0 1 0 ... 1 0 2]


## CONFUSSION MATRIX AND CLASSIFICATION REPORT FOR MULTINOMIAL NAIVE BAYES

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report


In [ ]:
cm = confusion_matrix(ypred_m1,y_test)
cm      

array([[2145,  319,  623],
       [ 344,  917,  400],
       [ 517,  347, 2530]], dtype=int64)

In [ ]:
print(classification_report(y_test,ypred_m1))

              precision    recall  f1-score   support

           0       0.69      0.71      0.70      3006
           1       0.55      0.58      0.57      1583
           2       0.75      0.71      0.73      3553

    accuracy                           0.69      8142
   macro avg       0.66      0.67      0.67      8142
weighted avg       0.69      0.69      0.69      8142



# SVM CLASSIFICATION

In [ ]:
from sklearn.svm import SVC

In [ ]:
m1 = SVC(kernel='linear',C=1)
m1.fit(x_train,y_train)



SVC(C=1, kernel='linear')

## PREDICTION THE SENTIMENT

In [ ]:
ypred_m1 = m1.predict(x_test)
print("The predicted sentiment",ypred_m1)


The predicted sentiment [0 1 1 ... 1 0 2]


### Confusion matrix and classification report for svm classifier

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

## APPLYING SVM WITH RBF KERNAL  

In [ ]:
m2 = SVC(kernel='rbf',gamma=0.1,C=0.1)
m2.fit(x_train,y_train)

SVC(C=0.1, gamma=0.1)

In [ ]:
print('Training Score',m2.score(x_train,y_train))
print('Testing Score',m2.score(x_test,y_test))

In [ ]:
cm_2 = confusion_matrix(ypred_m2,y_test)
cm_2 

In [ ]:
print(classification_report(y_test,ypred_m2))

## APPLYING SVM WITH POLY KERNAL 

In [ ]:
print('Training Score',m3.score(x_train,y_train))
print('Testing Score',m3.score(x_test,y_test))

In [ ]:
cm_3 = confusion_matrix(ypred_m3,y_test)
cm_3


In [ ]:
print(classification_report(y_test,ypred_m3))

# K-Nearest Neighbors CLASSIFICATION

In [171]:
from sklearn.neighbors import KNeighborsClassifier

In [172]:
m2 = KNeighborsClassifier(n_neighbors=11) #k=11
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

## PREDICTING THE SENTIMENT

In [173]:

ypred_m2 = m2.predict(x_test)
print("The predicted sentiment",ypred_m2)


The predicted sentiment [1 1 1 ... 1 1 0]


In [123]:

print("training score",m2.score(x_train,y_train))
print("testing score",m2.score(x_test,y_test))

training score 0.3608797451349173
testing score 0.3104083512434756


### CONFUSION MATRIX AND CLASSIFICATION REPORT FOR KNN CLASSIFICATION

In [124]:
cm_1 = confusion_matrix(ypred_m2,y_test)
cm_1     

array([[ 480,   41,  205],
       [1836, 1184, 2333],
       [  55,   22,  358]], dtype=int64)

In [125]:
print(classification_report(y_test,ypred_m2))


              precision    recall  f1-score   support

           0       0.66      0.20      0.31      2371
           1       0.22      0.95      0.36      1247
           2       0.82      0.12      0.21      2896

    accuracy                           0.31      6514
   macro avg       0.57      0.43      0.29      6514
weighted avg       0.65      0.31      0.28      6514



# LOGESTICREGRESSION

In [126]:
from sklearn.linear_model import LogisticRegression

In [127]:
m3 = LogisticRegression()

### PREDICTION

In [128]:

m3.fit(x_train,y_train) # ml model will be trained on training data
ypred_m3 = m3.predict(x_test) # ml model trained on training data is used to generate the predictions on the test data     
print("The predicted sentiment",ypred_m3)            

The predicted sentiment [2 1 1 ... 1 1 0]


c:\Users\deept\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# ACCURACY

In [129]:

print("training score",m3.score(x_train,y_train))
print("testing score",m3.score(x_test,y_test))

training score 0.8367942271523433
testing score 0.7723365059871047


## CONFUSION MATRIX AND CLASSIFICATION REPORT FOR LOGESTIC REGRESSION

In [130]:
cm2 = confusion_matrix(ypred_m3,y_test)
cm2      

array([[1792,  190,  321],
       [ 243,  874,  210],
       [ 336,  183, 2365]], dtype=int64)

In [131]:
print(classification_report(y_test,ypred_m3))

              precision    recall  f1-score   support

           0       0.78      0.76      0.77      2371
           1       0.66      0.70      0.68      1247
           2       0.82      0.82      0.82      2896

    accuracy                           0.77      6514
   macro avg       0.75      0.76      0.75      6514
weighted avg       0.77      0.77      0.77      6514

